name: DevOps pipeline
on: [push]
jobs:
   Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Python environment
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testing
        run: |
          coverage run -m pytest
      - name: Coverage
        run: |
          coverage report

  
  Build:
    runs-on: ubuntu-latest
    needs : 
      - Test
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-express:latest
  
  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.EC2_HOSTNAME }}
          USER_NAME: ubuntu

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            sudo docker container stop sinda_bochra_app
            sudo docker container rm sinda_bochra_app
            sudo docker image rm ${{ secrets.DOCKER_HUB_USERNAME }}/my-express
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-express:latest
            sudo docker run -d -p 80:3000 --name sinda_bochra_app ${{ secrets.DOCKER_HUB_USERNAME }}/my-express 
          '
